FROM node:18-alpine as builder

WORKDIR /app
COPY package.json .
RUN npm install
COPY . .

RUN npm run build

FROM nginx:1.25.4
COPY nginx.conf /etc/nginx/conf.d/default.conf

WORKDIR /usr/share/nginx/html
COPY nginx-entrypoint.sh /
COPY --from=builder /app/dist ./

ENTRYPOINT [ "bash", "/nginx-entrypoint.sh" ]