apiVersion: skaffold/v2beta9
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/data-depl.yaml
      - ./infra/k8s/search-depl.yaml
      - ./infra/k8s-prod/client-depl.yaml
build:
  local:
    push: false
  artifacts:
    - image: case-tracker-base
      context: utils
    - image: szpada87/case-client
      context: client
      docker:
        dockerfile: Dockerfile.prod
    - image: szpada87/case-search
      context: search
      requires:
        - image: case-tracker-base
          alias: BASE
      docker:
        dockerfile: Dockerfile
    - image: szpada87/case-data
      context: data
      requires:
        - image: case-tracker-base
          alias: BASE
      docker:
        dockerfile: Dockerfile
