apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: szpada87/case-client
          env:
            - name: VITE_AUTH_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: auth-domain
                  key: AUTH_DOMAIN
            - name: VITE_AUTH_AUDIENCE
              valueFrom:
                secretKeyRef:
                  name: auth-audience
                  key: AUTH_AUDIENCE
            - name: VITE_AUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: auth-client-id
                  key: AUTH_CLIENT_ID
            - name: VITE_BASE_PATH
              valueFrom:
                secretKeyRef:
                  name: base-path
                  key: BASE_PATH
---
apiVersion: v1
kind: Service
metadata:
  name: client-srv
spec:
  selector:
    app: client
  ports:
    - name: client
      protocol: TCP
      port: 3000
      targetPort: 5173
