name: deploy-search

on:
  push:
    branches:
      - main
    paths:
      - 'search/**'
      - 'utils/**'

jobs:
  build-utils:
    uses: ./.github/workflows/deploy-utils.yaml
    secrets: inherit
  build:
    needs: build-utils
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl registry login
      - run: cd search && docker build -f Dockerfile.prod -t szpada87/case-tracker:search .
      - run: docker tag szpada87/case-tracker:search registry.digitalocean.com/szpada87/case-tracker:search
      - run: docker push registry.digitalocean.com/szpada87/case-tracker:search
      - run: doctl kubernetes cluster kubeconfig save szpada87
      - run: kubectl rollout restart deployment search-depl
